name: approve-and-merge-dev-pr
on:
  pull_request:
    branches:
      - dev

permissions:
  pull-requests: write  # Explicitly grant write permissions for pull requests
  contents: write       # Grant write permissions for repository contents

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Approve Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })

      - name: Perform Merge Operations
        run: |
          git checkout main
          git pull origin main
          git checkout dev
          git pull origin dev
          git merge dev
          git push origin main
